Map recipe
Wolox/wolmo-cookbook-android pull request #42
Opened 2021-12-09 17:18 UTC by Marcosnr97

### Summary

- Added implementation for Google Maps
- Added marker clustering and current user location to map.
You can check other utilities available in the maps library [here](https://developers.google.com/maps/documentation/android-sdk/utility?hl=es-419)

Note: The map need an API Key to work so to set it up you need to add it in the Manifest

### Screenshot

![image](https://user-images.githubusercontent.com/42147220/145444569-d5f5e3fb-2e23-4124-afbc-d2597eec9001.png)

2021-12-09 18:32 UTC, LisandroDiMeo approved these changes

2021-12-09 18:56 UTC, bdecorneliis approved these changes
Nice work!

2021-12-09 18:56 UTC, bdecorneliis commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +        var lng = -58.838345
You could put them into companion object

2021-12-10 14:21 UTC, ffasitella requested changes
There are some minor issues to fix before merging

2021-12-10 14:21 UTC, ffasitella commented on README.md
> +16. <b>[Google Maps](https://github.com/Wolox/wolmo-cookbook-android/tree/master/app/src/main/java/ar/com/wolox/android/cookbook/maps):</b> Implementation of Google Maps with clustering and current l
It's the 18th one!

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/AndroidManifest.xml
> +            android:value="" />
We should leave a comment about how to make this work properly.

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +        map.setOnMarkerClickListener(clusterManager)
You can use `with(map)`

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +                MyItem(lat, lng, "Title $i", "Snippet $i")
You can save these strings as resources.

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +        map.uiSettings.isMyLocationButtonEnabled = true
You can use a kotlin function to avoid calling map twice. Also, be careful with those blank spaces.

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +    }
Move the companion object to the very bottom of the class.

2021-12-10 14:21 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/cookbook/maps/MapFragment.kt
> +class MapFragment : WolmoFragment<FragmentMapBinding, MapPresenter>(), MapView,
MapPresenter is an empty class, so you can do this: `WolmoFragment<FragmentMapBinding, Any>()`

2021-12-15 12:51 UTC, ffasitella approved these changes
Amazing! 👏🏽 👏🏽

2021-12-16 13:22 UTC, merged